name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

change-template: '- $TITLE by @$AUTHOR in [#$NUMBER](https://github.com/$OWNER/$REPOSITORY/pull/$NUMBER)'
category-template: '### $TITLE'
template: |
  <TODO: summary of changes here>
  
  $CHANGES
    
  **Full Changelog**: [$PREVIOUS_TAG...$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)


version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  default: patch


autolabeler:
  - label: 'breaking'
    title:
      - '/.*!:.*/'
  - label: 'feature'
    title:
      - '/feat.*/'
  - label: 'fix'
    title:
      - '/fix.*/'
      - '/bug.*/'
  - label: 'chore'
    title:
      - '/chore.*/'
#    files:
#      - '*.md'
#      - '*.txt'
  - label: 'documentation'
    title:
      - '/docs.*/'
  - label: 'refactor'
    title:
      - '/ref.*/'
      - '/refactor.*/'
  - label: 'style'
    title:
      - '/style.*/'
  - label: 'performance'
    title:
      - '/perf:.*/'
      - '/performance:.*/'
  - label: 'test'
    title:
      - '/test.*/'
#    files:
#      - 'tests/*'
  - label: 'ci'
    title:
      - '/ci.*/'
#    files:
#      - '.github/*'
  - label: 'dependencies'
    title:
      - '/.*deps.*:.*/'
#    files:
#      - 'requirements*'


exclude-labels:
  - 'skip-changelog'

exclude-contributors:
  - 'manytask-bot'
  - 'manytask-service'


categories:
  - title: 'Breaking'
    label: 'breaking'
  - title: 'Features'
    label: 'feature'
  - title: 'Fixes'
    label: 'fix'
  - title: 'Tests and CI/CD'
    labels: ['test', 'ci']
  - title: 'Enhancement'
    labels: ['enhancement', 'refactor', 'performance', 'style']
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Other changes'
  - title: 'Dependency Updates'
    label: 'dependencies'
#    collapse-after: 5
